### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by merbla**
* Initial release matching `Serilog.AspNetCore`

### CODE REVIEW

**Comment by nblumhardt** [comment]
Anything more needed for this one folks?

**Comment by merbla** [comment]
LGTM, @nblumhardt was the trigger on the AppVeyor side?

**Comment by andrewlock** [comment]
LGTM 🙂

**Comment by nblumhardt** [comment]
@merbla needed the webhook registered under the GitHub repo's settings 👍 

🍾

**Pull request merged**
