### PR TITLE
A bootstrap logger

### PR DESCRIPTION
**Pull request by nblumhardt**
We want to configure Serilog as soon as possible during program start-up, so that errors during start-up are logged. But, many logging-relevant services are not available until part-way through host bootstrapping. Instead of being stuck with an either/or choice, this PR attempts to address both requirements:

 1. During start-up, a special "bootstrap logger" is assigned to the static `Log.Logger`
 2. Later, once host services are available, the bootstrap logger is reconfigured and then frozen

Overall, there should be no regressions for existing code, since this mechanism is opt-in using the new bootstrap logger type (though I've taken the liberty of updating minimum framework/dependency versions, which is a breaking change).

Code using this path should suffer little to no performance penalty, since the `Logger` that ends up registered with the host is the underlying frozen/final logger.

## Example

There's a web application example included in the changeset. Its `Program.cs` looks like this:

```csharp
public static class Program
{
    public static int Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .WriteTo.Console()
            .CreateBootstrapLogger();
        
        Log.Information("Starting up!");

        try
        {
            CreateHostBuilder(args).Build().Run();

            Log.Information("Stopped cleanly");
            return 0;
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "An unhandled exception occured during bootstrapping");
            return 1;
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .UseSerilog((context, services, configuration) => configuration
                .WriteTo.Console()
                .ReadFrom.Configuration(context.Configuration)
                .ReadFrom.Services(services))
            .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
}
```

Initially, a console logger is configured. Note the use of `CreateBootstrapLogger()`, a new method in this PR.

We write an event through it, and if bootstrapping fails, we'll also write the exception to it. The initial logger could be configured using any combination of sinks, etc.

Then, in `CreateHostBuilder()`, the logger is reconfigured: we again add `Console`, but also read from `appSettings.json` to add a file logger, and inject sinks etc. from the `IServiceProvider` (also a new method, here).

The output to the console is:

```
[17:04:19 INF] Starting up!
[17:04:19 INF] Now listening on: https://localhost:5001
[17:04:19 INF] Now listening on: http://localhost:5000
[17:04:19 INF] Application started. Press Ctrl+C to shut down.
[17:04:19 INF] Hosting environment: Development
[17:04:19 INF] Content root path: C:\Development\nblumhardt\serilog-extensions-hosting\samples\WebApplicationSample
[17:04:19 INF] Saying hello
[17:04:52 INF] Application is shutting down...
[17:04:52 INF] Stopped cleanly
```

Note the initial "Starting up!".

The output to the log file is:

```
2020-10-07 17:04:19.669 +10:00 [INF] Now listening on: https://localhost:5001
2020-10-07 17:04:19.699 +10:00 [INF] Now listening on: http://localhost:5000
2020-10-07 17:04:19.700 +10:00 [INF] Application started. Press Ctrl+C to shut down.
2020-10-07 17:04:19.701 +10:00 [INF] Hosting environment: Development
2020-10-07 17:04:19.702 +10:00 [INF] Content root path: C:\Development\nblumhardt\serilog-extensions-hosting\samples\WebApplicationSample
2020-10-07 17:04:19.979 +10:00 [INF] Saying hello
2020-10-07 17:04:52.511 +10:00 [INF] Application is shutting down...
2020-10-07 17:04:52.532 +10:00 [INF] Stopped cleanly
```

Note the final "Stopped cleanly" - the reconfigured logger outlives the host.

### CODE REVIEW

**Comment by nblumhardt** [comment]
@serilog/reviewers-core I think this is ready to go :-)

**Review by adamchester — APPROVED** [review]
LGTM

**Comment by nblumhardt** [comment]
Thanks @adamchester

**Comment by adamchester-loanmarket** [comment]
> Thanks @adamchester

Thank you for the awesome new feature 🥇

**Comment by adamchester** [comment]
> Thanks @adamchester

Thank you for the awesome new feature 🥇

**Pull request merged**
