### PR TITLE
.NET 8 RC 2

### PR DESCRIPTION
**Pull request by nblumhardt**
WIP, still needs a Serilog.Settings.Configuration update.

### CODE REVIEW

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/Serilog.Settings.Configuration/8.0.0

**Comment by sungam3r** [comment]
It think that PR outdated.

**Comment by bartelink** [comment]
@nblumhardt abandon?

**Comment by nblumhardt** [comment]
Thanks @bartelink :+1:

**Pull request closed without merging**
